Update travis yml file to mostly exclude branchs

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -2,12 +2,19 @@ sudo: required
 language: python
 python:
   - '3.5'
-install:
-  - pip install -e .
-  - pip install -r tests/requirements.txt
 services:
   - redis-server
   - docker
+branches:
+  # Restrict push builds to only master
+  only:
+  - master
+before_install:
+  # Fail immediately on any error
+  - set -e
+install:
+  - pip install -e .
+  - pip install -r tests/requirements.txt
 before_script:
   - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
   - chmod +x ./cc-test-reporter
@@ -16,10 +23,6 @@ script:
   - flake8 --ignore E501 --exclude *__init__.py ./
   - make build-testbed
   - py.test --cov=scoring_engine --cov-report=xml:coverage.xml tests
-after_script:
-  - >
-      if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then \
-        ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT ;\
-      else \
-        exit 0 ;\
-      fi
+after_success:
+  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
+  if: type = push
